"""Test for Hallucination Bait Detection (v4.10, #377).

Verifies detection of patterns that may cause LLM hallucinations:
- Unsourced statistics
- Absolute claims
- Speculative data
- Vague ranges
- AI content without disclaimer
- Self-citations
- Missing measurement units
- Medical claims
"""

from __future__ import annotations

from bs4 import BeautifulSoup

from geo_optimizer.core.hallucination_bait import (
    audit_hallucination_bait,
)
from geo_optimizer.models.results import ContentResult, MetaResult, SchemaResult


def _content(h1="", word_count=500, description=""):
    return ContentResult(
        word_count=word_count,
        h1_text=h1,
        heading_count=3,
        has_h1=bool(h1),
    )


def _meta(title="", description=""):
    return MetaResult(
        has_title=bool(title),
        title_text=title,
        description_text=description,
    )


def _schema():
    return SchemaResult()


class TestHallucinationBait:
    """Unit tests for hallucination-bait analysis."""

    def test_none_soup_returns_unchecked(self):
        """None soup → checked=False, zero baits."""
        result = audit_hallucination_bait(None, "", _content(), _meta(), _schema())
        assert result.checked is False
        assert result.total_baits == 0
        assert result.severity == "clean"

    def test_clean_page_no_baits(self):
        """Clean page → no baits detected."""
        html = (
            "<html><body><main>"
            "<h1>Welcome to Our Site</h1>"
            "<p>We provide quality services since 2010.</p>"
            "</main></body></html>"
        )
        soup = BeautifulSoup(html, "html.parser")
        result = audit_hallucination_bait(soup, html, _content(h1="Welcome"), _meta(), _schema())
        assert result.checked is True
        assert result.total_baits == 0
        assert result.severity == "clean"

    def test_unsourced_statistics(self):
        """Unsourced statistics → detected."""
        html = (
            "<html><body><main>"
            "<h1>SEO Statistics 2025</h1>"
            "<p>Over 67% of all searches are now AI-powered.</p>"
            "<p>Organic traffic dropped by 23% last year.</p>"
            "</main></body></html>"
        )
        soup = BeautifulSoup(html, "html.parser")
        result = audit_hallucination_bait(soup, html, _content(h1="SEO Statistics"), _meta(), _schema())
        assert result.unsourced_stats >= 2
        assert result.total_baits > 0
        assert len(result.unsourced_stats_samples) > 0

    def test_absolute_claims(self):
        """Affermazioni assolute → rilevate."""
        html = (
            "<html><body><main>"
            "<h1>Health Facts</h1>"
            "<p>Studies show that exercise cures depression.</p>"
            "<p>Research proves that diet prevents cancer.</p>"
            "</main></body></html>"
        )
        soup = BeautifulSoup(html, "html.parser")
        result = audit_hallucination_bait(soup, html, _content(h1="Health Facts"), _meta(), _schema())
        assert result.absolute_claims >= 2
        assert len(result.absolute_claims_samples) > 0

    def test_speculative_statements(self):
        """Proiezioni future senza fonte → rilevate."""
        html = (
            "<html><body><main>"
            "<h1>Future of AI</h1>"
            "<p>By 2030, AI will replace 50% of all jobs.</p>"
            "<p>By the year 2030, AI is expected to surpass human intelligence.</p>"
            "<p>Si prevede che il mercato raggiunga 100 miliardi.</p>"
            "</main></body></html>"
        )
        soup = BeautifulSoup(html, "html.parser")
        result = audit_hallucination_bait(soup, html, _content(h1="Future of AI"), _meta(), _schema())
        assert result.speculative_statements >= 2

    def test_ai_generated_without_disclaimer(self):
        """Contenuto AI senza disclaimer → rilevato."""
        html = (
            "<html><body><main>"
            "<h1>AI Content</h1>"
            "<p>This article was generated by ChatGPT.</p>"
            "<p>AI-generated content for your reading pleasure.</p>"
            "</main></body></html>"
        )
        soup = BeautifulSoup(html, "html.parser")
        result = audit_hallucination_bait(soup, html, _content(h1="AI Content"), _meta(), _schema())
        assert result.ai_generated_signals > 0

    def test_ai_generated_with_disclaimer(self):
        """Contenuto AI CON disclaimer → NON rilevato."""
        html = (
            "<html><body><main>"
            "<h1>AI Content</h1>"
            "<p>This article was generated by ChatGPT.</p>"
            "<p>Disclaimer: This is not medical advice.</p>"
            "<p>AI-generated content for educational purposes only.</p>"
            "</main></body></html>"
        )
        soup = BeautifulSoup(html, "html.parser")
        result = audit_hallucination_bait(soup, html, _content(h1="AI Content"), _meta(), _schema())
        assert result.ai_generated_signals == 0

    def test_ai_generated_bare_assistant_mention_not_flagged(self):
        """Naming an assistant is not declaring machine authorship (#4.16.3).

        This is the ordinary copy of any site writing about AI search — the exact
        audience this tool serves. The pattern used to match the bare product names
        and report the page as undisclosed AI content at severity high.
        """
        html = (
            "<html><body><main>"
            "<h1>Find the gaps that keep your site out of AI answers</h1>"
            "<p>Find crawler, llms.txt, schema, content, and citation gaps that stop "
            "ChatGPT, Perplexity, Claude, and Gemini from citing your site.</p>"
            "<p>GEO is the practice of making websites citable by AI search engines "
            "such as ChatGPT, Perplexity, Claude, and Gemini.</p>"
            "</main></body></html>"
        )
        soup = BeautifulSoup(html, "html.parser")
        result = audit_hallucination_bait(soup, html, _content(h1="AI answers"), _meta(), _schema())
        assert result.ai_generated_signals == 0
        assert result.ai_generated_samples == []

    def test_ai_generated_authoring_verb_still_flagged(self):
        """A construct that does declare machine authorship is still caught (#4.16.3)."""
        for phrase in (
            "This post was written by ChatGPT.",
            "Article created with Claude.",
            "This page was drafted using an LLM.",
        ):
            html = f"<html><body><main><h1>T</h1><p>{phrase}</p></main></body></html>"
            soup = BeautifulSoup(html, "html.parser")
            result = audit_hallucination_bait(soup, html, _content(h1="T"), _meta(), _schema())
            assert result.ai_generated_signals > 0, f"non rilevato: {phrase}"

    def test_medical_claims(self):
        """Affermazioni mediche → rilevate."""
        html = (
            "<html><body><main>"
            "<h1>Natural Cures</h1>"
            "<p>This herb cures diabetes.</p>"
            "<p>Vitamin C prevents cancer.</p>"
            "<p>Guarisce il raffreddore in 24 ore.</p>"
            "</main></body></html>"
        )
        soup = BeautifulSoup(html, "html.parser")
        result = audit_hallucination_bait(soup, html, _content(h1="Natural Cures"), _meta(), _schema())
        assert result.medical_claims > 0
        assert len(result.medical_claim_samples) > 0

    def test_severity_levels(self):
        """Livelli di severita corretti."""
        # Clean
        html = "<html><body><main><h1>Clean</h1><p>Safe content.</p></main></body></html>"
        soup = BeautifulSoup(html, "html.parser")
        result = audit_hallucination_bait(soup, html, _content("Clean"), _meta(), _schema())
        assert result.severity == "clean"

        # Low
        html = "<html><body><main><h1>Low</h1><p>Studies show it works.</p></main></body></html>"
        soup = BeautifulSoup(html, "html.parser")
        result = audit_hallucination_bait(soup, html, _content("Low"), _meta(), _schema())
        assert result.severity == "low"

        # High
        html = (
            "<html><body><main><h1>High</h1>"
            "<p>Studies show it works. By 2030 all jobs gone.</p>"
            "<p>This cures diabetes. Generated by AI.</p>"
            "<p>Research proves 90% effectiveness. Up to 50 million cases.</p>"
            "<p>According to our data, it's 100% safe. Vitamin C prevents cancer.</p>"
            "</main></body></html>"
        )
        soup = BeautifulSoup(html, "html.parser")
        result = audit_hallucination_bait(soup, html, _content("High"), _meta(), _schema())
        assert result.total_baits >= 6
        assert result.severity == "high"

    def test_details_populated(self):
        """Detail strings contengono descrizioni."""
        html = (
            "<html><body><main>"
            "<h1>Bad Content</h1>"
            "<p>Studies show 100% effectiveness.</p>"
            "<p>This cures everything.</p>"
            "</main></body></html>"
        )
        soup = BeautifulSoup(html, "html.parser")
        result = audit_hallucination_bait(soup, html, _content("Bad"), _meta(), _schema())
        assert len(result.details) > 0
        assert "source" in result.details[0].lower() or "claim" in result.details[0].lower()

    def test_samples_limited_to_3(self):
        """Samples limitati a max 3 per categoria."""
        html = (
            "<html><body><main>"
            "<h1>Stats</h1>"
            "<p>10% of users, 20% of users, 30% of users, "
            "40% of users, 50% of users, 60% of users</p>"
            "</main></body></html>"
        )
        soup = BeautifulSoup(html, "html.parser")
        result = audit_hallucination_bait(soup, html, _content("Stats"), _meta(), _schema())
        assert result.unsourced_stats >= 6
        assert len(result.unsourced_stats_samples) <= 3
