"""
Automatic GEO fix generator.

Analyzes an AuditResult and generates corrective artifacts:
- robots.txt with missing AI bots
- Complete llms.txt via sitemap
- Missing JSON-LD schemas (WebSite, FAQPage, Organization)
- Missing HTML meta tags
- Content rewrite guidance for weak citation signals

All functions return dataclasses (FixItem/FixPlan), NEVER print.
"""

from __future__ import annotations

import copy
import html as html_lib
import json
import logging
from urllib.parse import urlparse

from geo_optimizer.models.config import AI_BOTS, SAMEAS_AUTHORITATIVE_DOMAINS, SCHEMA_TEMPLATES
from geo_optimizer.models.results import AuditResult, FixItem, FixPlan

logger = logging.getLogger(__name__)


def generate_robots_fix(result: AuditResult, base_url: str, project_config=None) -> FixItem | None:
    """Generate robots.txt patch with missing AI bots.

    If robots.txt not found: generates complete file with all bots.
    If found but with missing bots: generates lines to append.
    Uses project_config.extra_bots if provided (#422).

    Returns:
        FixItem or None if no fix needed.
    """
    if result.robots.found and not result.robots.bots_missing and not result.robots.bots_blocked:
        return None

    # Fix #422: merge extra_bots from project config (same as run_full_audit)
    effective_bots = dict(AI_BOTS)
    if project_config is not None and getattr(project_config, "extra_bots", None):
        effective_bots.update(project_config.extra_bots)

    if not result.robots.found:
        # Generate complete robots.txt
        lines = [
            "# Robots.txt — optimized for AI search engines",
            "# Generated by GEO Optimizer (https://github.com/auriti-labs/geo-optimizer-skill)",
            "",
            "User-agent: *",
            "Allow: /",
            "",
        ]
        for bot, description in effective_bots.items():
            lines.append(f"# {description}")
            lines.append(f"User-agent: {bot}")
            lines.append("Allow: /")
            lines.append("")

        # Sitemap placeholder
        parsed = urlparse(base_url)
        lines.append(f"Sitemap: {parsed.scheme}://{parsed.netloc}/sitemap.xml")
        lines.append("")

        return FixItem(
            category="robots",
            description=f"Create robots.txt with access for all {len(effective_bots)} AI bots",
            content="\n".join(lines),
            file_name="robots.txt",
            action="create",
        )

    # robots.txt exists but some bots are missing or blocked
    # Fix #211: also include bots_blocked — a bot blocked with Disallow
    # still needs an Allow rule to become accessible
    bots_to_fix = result.robots.bots_missing + result.robots.bots_blocked
    lines = [
        "",
        "# ─── Missing AI bots (added by GEO Optimizer) ───",
        "",
    ]
    for bot in bots_to_fix:
        description = effective_bots.get(bot, "AI bot")
        lines.append(f"# {description}")
        lines.append(f"User-agent: {bot}")
        lines.append("Allow: /")
        lines.append("")

    return FixItem(
        category="robots",
        description=f"Add {len(bots_to_fix)} missing/blocked AI bots to robots.txt",
        content="\n".join(lines),
        file_name="robots.txt",
        action="append",
    )


def generate_llms_fix(result: AuditResult, base_url: str) -> FixItem | None:
    """Generate llms.txt using the site's sitemap.

    If llms.txt not found or incomplete: generates complete version.

    Returns:
        FixItem or None if llms.txt is already complete.
    """
    if result.llms.found and result.llms.has_h1 and result.llms.has_sections and result.llms.has_links:
        return None

    from geo_optimizer.core.llms_generator import discover_sitemap, fetch_sitemap, generate_llms_txt

    # Try to discover the sitemap
    sitemap_url = discover_sitemap(base_url)
    urls = []
    if sitemap_url:
        urls = fetch_sitemap(sitemap_url)

    # Generate llms.txt content
    parsed = urlparse(base_url)
    site_name = parsed.netloc.replace("www.", "")
    content = generate_llms_txt(
        base_url=base_url,
        urls=urls,
        site_name=site_name,
        description=f"Information about {site_name} for AI search engines",
        fetch_titles=False,
        max_urls_per_section=20,
    )

    action = "create" if not result.llms.found else "overwrite"
    desc = "Create llms.txt" if not result.llms.found else "Regenerate llms.txt with complete structure"

    if urls:
        desc += f" ({len(urls)} URLs from sitemap)"

    return FixItem(
        category="llms",
        description=desc,
        content=content,
        file_name="llms.txt",
        action=action,
    )


def generate_schema_fix(result: AuditResult, base_url: str) -> list[FixItem]:
    """Generate missing JSON-LD schemas.

    Checks WebSite, FAQPage and Organization. For each missing type,
    generates the template populated with available data.

    Returns:
        List of FixItem (may be empty).
    """
    fixes = []
    parsed = urlparse(base_url)
    site_name = parsed.netloc.replace("www.", "")

    # WebSite schema
    if not result.schema.has_website:
        template = copy.deepcopy(SCHEMA_TEMPLATES["website"])
        from geo_optimizer.core.schema_injector import fill_template

        values = {
            "name": result.meta.title_text or site_name,
            "url": base_url,
            "description": result.meta.description_text or f"Website {site_name}",
        }
        schema = fill_template(template, values)
        fixes.append(
            FixItem(
                category="schema",
                description="Generate WebSite JSON-LD schema",
                content=json.dumps(schema, indent=2, ensure_ascii=False),
                file_name="schema-website.jsonld",
                action="snippet",
            )
        )

    # FAQPage schema — generate example FAQ structure if missing (#fix-faq-schema)
    if not result.schema.has_faq:
        faq_schema = {
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": [
                {
                    "@type": "Question",
                    "name": f"Cos'è {site_name}?",
                    "acceptedAnswer": {
                        "@type": "Answer",
                        "text": result.meta.description_text or f"Descrizione di {site_name}.",
                    },
                },
                {
                    "@type": "Question",
                    "name": f"Come contattare {site_name}?",
                    "acceptedAnswer": {
                        "@type": "Answer",
                        "text": f"Visita la pagina contatti su {base_url}/contatti",
                    },
                },
            ],
        }
        fixes.append(
            FixItem(
                category="schema",
                description="Generate FAQPage JSON-LD schema with example Q&A",
                content=json.dumps(faq_schema, indent=2, ensure_ascii=False),
                file_name="schema-faqpage.jsonld",
                action="snippet",
            )
        )

    # Organization schema
    if "Organization" not in result.schema.found_types:
        template = copy.deepcopy(SCHEMA_TEMPLATES["organization"])
        from geo_optimizer.core.schema_injector import fill_template

        values = {
            "name": result.meta.title_text or site_name,
            "url": base_url,
            "description": result.meta.description_text or "",
            "logo_url": f"{base_url}/logo.png",
        }
        # sameAs placeholder URLs are already embedded in the template (#398).
        # They use authoritative domains from SAMEAS_AUTHORITATIVE_DOMAINS
        # (linkedin.com, github.com, twitter.com) — the most important signal
        # for brand_kg_readiness (3pt). The user must replace YOUR_COMPANY /
        # YOUR_ORG / YOUR_HANDLE with real profile identifiers.
        _ = SAMEAS_AUTHORITATIVE_DOMAINS  # imported for documentation clarity
        schema = fill_template(template, values)
        fixes.append(
            FixItem(
                category="schema",
                description="Generate Organization JSON-LD schema with sameAs placeholders",
                content=json.dumps(schema, indent=2, ensure_ascii=False),
                file_name="schema-organization.jsonld",
                action="snippet",
            )
        )

    return fixes


def generate_meta_fix(result: AuditResult, base_url: str) -> FixItem | None:
    """Generate missing HTML meta tags.

    Checks title, description, canonical, Open Graph and generates
    missing tags as HTML snippets to insert in the <head>.

    Returns:
        FixItem or None if all meta tags are present.
    """
    parsed = urlparse(base_url)
    site_name = parsed.netloc.replace("www.", "")
    tags = []

    # Escape all values derived from the target site to prevent
    # HTML injection when the user inserts the snippet in their <head> (fix #180)
    safe_site = html_lib.escape(site_name, quote=True)
    safe_url = html_lib.escape(base_url, quote=True)

    if not result.meta.has_title:
        tags.append(f"<title>{safe_site}</title>")

    if not result.meta.has_description:
        tags.append(f'<meta name="description" content="Website {safe_site}">')

    if not result.meta.has_canonical:
        tags.append(f'<link rel="canonical" href="{safe_url}/">')

    if not result.meta.has_og_title:
        title = html_lib.escape(result.meta.title_text or site_name, quote=True)
        tags.append(f'<meta property="og:title" content="{title}">')

    if not result.meta.has_og_description:
        desc = html_lib.escape(result.meta.description_text or f"Website {site_name}", quote=True)
        tags.append(f'<meta property="og:description" content="{desc}">')

    if not result.meta.has_og_image:
        tags.append(f'<meta property="og:image" content="{safe_url}/og-image.png">')

    if not tags:
        return None

    return FixItem(
        category="meta",
        description=f"Generate {len(tags)} missing meta tags",
        content="\n".join(tags),
        file_name="meta-tags.html",
        action="snippet",
    )


def generate_ai_discovery_fix(result: AuditResult, base_url: str) -> list[FixItem]:
    """Generate templates for missing AI discovery endpoints (geo-checklist.dev).

    Generates /ai/summary.json and /ai/faq.json if absent.
    Does NOT generate /.well-known/ai.txt (too server-specific).

    Returns:
        List of FixItem (may be empty).
    """
    fixes = []
    parsed = urlparse(base_url)
    site_name = parsed.netloc.replace("www.", "")

    # Template /ai/summary.json
    if not result.ai_discovery.has_summary or not result.ai_discovery.summary_valid:
        summary_data = {
            "name": result.meta.title_text or site_name,
            "description": result.meta.description_text or f"Website {site_name}",
            "url": base_url,
            "lastModified": "{{ISO_DATE}}",
        }
        fixes.append(
            FixItem(
                category="ai_discovery",
                description="Generate /ai/summary.json with site information for AI",
                content=json.dumps(summary_data, indent=2, ensure_ascii=False),
                file_name="ai/summary.json",
                action="create",
            )
        )

    # Template /ai/faq.json
    if not result.ai_discovery.has_faq:
        faq_data = {
            "faqs": [
                {
                    "question": f"What is {site_name}?",
                    "answer": result.meta.description_text or f"A website about {site_name}.",
                },
                {
                    "question": f"How can I use {site_name}?",
                    "answer": f"Visit {base_url} to get started.",
                },
            ]
        }
        fixes.append(
            FixItem(
                category="ai_discovery",
                description="Generate /ai/faq.json with example FAQ for AI",
                content=json.dumps(faq_data, indent=2, ensure_ascii=False),
                file_name="ai/faq.json",
                action="create",
            )
        )

    return fixes


def generate_content_rewrite_fix(result: AuditResult, base_url: str) -> FixItem | None:
    """Generate deterministic rewrite guidance for content weaknesses.

    Returns:
        FixItem or None if content signals are already strong.
    """
    suggestions: list[str] = []
    page_label = result.content.h1_text or result.meta.title_text or base_url

    if not result.content.has_h1:
        suggestions.append(
            "- Add a single H1 that states the page topic explicitly and matches the user's likely query intent."
        )
    if result.content.word_count < 300:
        suggestions.append(
            "- Expand the page to at least 300 words with one intro, 2-3 H2 sections, and one concise closing summary."
        )
    if not result.content.has_front_loading:
        suggestions.append(
            "- Rewrite the opening 150 characters so they answer the core question immediately before any background context."
        )
    if not result.content.has_heading_hierarchy:
        suggestions.append(
            "- Split the body into H2/H3 sections so each section has one focused takeaway and one supporting paragraph."
        )
    if not result.content.has_lists_or_tables:
        suggestions.append(
            "- Add at least one bullet list or comparison table to make the page easier to chunk and quote."
        )
    if not result.content.has_numbers:
        suggestions.append("- Add concrete numbers, benchmarks, or dated facts instead of purely generic claims.")
    if not result.content.has_links:
        suggestions.append(
            "- Add 2-3 authoritative outbound citations near factual claims to improve credibility and extractability."
        )

    if not suggestions:
        return None

    content = "\n".join(
        [
            f"# Content Rewrite Plan — {page_label}",
            "",
            "Use this deterministic rewrite checklist before publishing the next revision.",
            "",
            "## Priority Suggestions",
            *suggestions,
            "",
            "## Recommended Section Shape",
            "- Intro: answer the main question in one direct sentence.",
            "- H2 1: explain the key concept with one concrete example.",
            "- H2 2: add evidence, numbers, or source-backed support.",
            "- H2 3: compare options, tradeoffs, or implementation steps.",
            "- Close: summarize the decision or takeaway in one citation-ready sentence.",
        ]
    )

    return FixItem(
        category="content",
        description="Generate deterministic rewrite suggestions for weak content signals",
        content=content,
        file_name="content-rewrite.md",
        action="snippet",
    )


def _estimate_score_after(result: AuditResult, fixes: list[FixItem]) -> int:
    """Estimate the score after applying the fixes.

    Calculates the delta as the difference between the maximum achievable score
    and the current score for each fixed category (fix #187).
    """
    from geo_optimizer.models.config import ROBOTS_PARTIAL_SCORE, SCORING

    bonus = 0
    categories_fixed = {f.category for f in fixes}

    if "robots" in categories_fixed:
        # Delta = maximum possible - current (fix #187, #203: inline to avoid core→cli import)
        max_robots = SCORING["robots_found"] + SCORING["robots_citation_ok"]
        current_robots = 0
        if result.robots.found:
            current_robots = SCORING["robots_found"]
            if result.robots.citation_bots_ok:
                current_robots += (
                    SCORING["robots_citation_ok"] if result.robots.citation_bots_explicit else ROBOTS_PARTIAL_SCORE
                )
            elif result.robots.bots_allowed:
                current_robots += ROBOTS_PARTIAL_SCORE
        bonus += max_robots - current_robots

    if "llms" in categories_fixed and not result.llms.found:
        # Fix #420: include all llms SCORING keys (was missing blockquote, depth, full)
        bonus += (
            SCORING["llms_found"]
            + SCORING["llms_h1"]
            + SCORING["llms_sections"]
            + SCORING["llms_links"]
            + SCORING.get("llms_blockquote", 0)
            + SCORING.get("llms_depth", 0)
            + SCORING.get("llms_full", 0)
        )

    if "schema" in categories_fixed:
        if not result.schema.has_website:
            bonus += SCORING["schema_website"]
        if not result.schema.has_faq:
            bonus += SCORING["schema_faq"]

    if "meta" in categories_fixed:
        if not result.meta.has_title:
            bonus += SCORING["meta_title"]
        if not result.meta.has_description:
            bonus += SCORING["meta_description"]
        if not result.meta.has_canonical:
            bonus += SCORING["meta_canonical"]
        if not result.meta.has_og_title and not result.meta.has_og_description:
            bonus += SCORING["meta_og"]

    if "ai_discovery" in categories_fixed:
        if not result.ai_discovery.has_summary or not result.ai_discovery.summary_valid:
            bonus += SCORING["ai_discovery_summary"]
        if not result.ai_discovery.has_faq:
            bonus += SCORING["ai_discovery_faq"]

    if "content" in categories_fixed:
        if not result.content.has_h1:
            bonus += SCORING["content_h1"]
        if not result.content.has_numbers:
            bonus += SCORING["content_numbers"]
        if not result.content.has_links:
            bonus += SCORING["content_links"]
        if result.content.word_count < 300:
            bonus += SCORING["content_word_count"]
        if not result.content.has_heading_hierarchy:
            bonus += SCORING.get("content_heading_hierarchy", 0)
        if not result.content.has_lists_or_tables:
            bonus += SCORING.get("content_lists_or_tables", 0)
        if not result.content.has_front_loading:
            bonus += SCORING.get("content_front_loading", 0)

    return min(100, result.score + bonus)


def run_all_fixes(
    url: str,
    audit_result: AuditResult | None = None,
    only: set[str] | None = None,
    project_config=None,
) -> FixPlan:
    """Orchestrator: runs audit if needed, generates all fixes.

    Args:
        url: Site URL.
        audit_result: Pre-computed AuditResult (avoids double audit).
        only: Set of categories to generate (e.g. {"robots", "llms"}).
              If None, generates all applicable fixes.

    Returns:
        FixPlan with all generated fixes and estimated score.
    """
    if audit_result is None:
        from geo_optimizer.core.audit import run_full_audit

        audit_result = run_full_audit(url)

    # Normalize URL
    base_url = audit_result.url

    fixes: list[FixItem] = []
    skipped: list[str] = []
    all_categories = {"robots", "llms", "schema", "meta", "ai_discovery", "content"}
    active = only if only else all_categories

    # Robots fix
    if "robots" in active:
        fix = generate_robots_fix(audit_result, base_url, project_config=project_config)
        if fix:
            fixes.append(fix)
        else:
            skipped.append("robots: all AI bots are already allowed")
    else:
        skipped.append("robots: excluded by --only filter")

    # LLMS fix
    if "llms" in active:
        fix = generate_llms_fix(audit_result, base_url)
        if fix:
            fixes.append(fix)
        else:
            skipped.append("llms: llms.txt is already complete")
    else:
        skipped.append("llms: excluded by --only filter")

    # Schema fix
    if "schema" in active:
        schema_fixes = generate_schema_fix(audit_result, base_url)
        fixes.extend(schema_fixes)
        if not schema_fixes:
            skipped.append("schema: all relevant schemas are present")
    else:
        skipped.append("schema: excluded by --only filter")

    # AI Discovery fix (v4.1: generate templates for AI discovery endpoints)
    if "ai_discovery" in active:
        ai_fixes = generate_ai_discovery_fix(audit_result, base_url)
        fixes.extend(ai_fixes)
        if not ai_fixes:
            skipped.append("ai_discovery: all AI discovery endpoints are already present")
    else:
        skipped.append("ai_discovery: excluded by --only filter")

    # Meta fix
    if "meta" in active:
        fix = generate_meta_fix(audit_result, base_url)
        if fix:
            fixes.append(fix)
        else:
            skipped.append("meta: all meta tags are present")
    else:
        skipped.append("meta: excluded by --only filter")

    # Content rewrite suggestions
    if "content" in active:
        fix = generate_content_rewrite_fix(audit_result, base_url)
        if fix:
            fixes.append(fix)
        else:
            skipped.append("content: content signals are already strong")
    else:
        skipped.append("content: excluded by --only filter")

    score_after = _estimate_score_after(audit_result, fixes)

    return FixPlan(
        url=base_url,
        score_before=audit_result.score,
        score_estimated_after=score_after,
        fixes=fixes,
        skipped=skipped,
    )
