"""Hallucination Bait Detection (#377).

Analyze page content to detect patterns that may cause LLM hallucinations:
unverifiable claims, unsourced statistics, imprecise data, speculative
extrapolations, AI-generated content without disclaimer.

Zero HTTP fetches — works only on already-available data.
Based on: UC Berkeley EMNLP 2024, Anthropic AI Safety Research 2025.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from geo_optimizer.models.results import ContentResult, MetaResult, SchemaResult

# ─── Hallucination-bait patterns ─────────────────────────────────────────────

# Unsourced statistics (numbers followed by % without citation)
_UNSOURCED_STAT_RE = re.compile(
    r"\b\d{1,3}(?:\.\d+)?%|\b\d{1,3}\s*(?:percent|per cento)\b",
    re.IGNORECASE,
)

# Absolute claims with certainty verbs
_ABSOLUTE_CLAIM_RE = re.compile(
    r"\b(studies show|research proves|evidence suggests|it is known|"
    r"studi dimostrano|la ricerca prova|evidenze suggeriscono|"
    r"si sa che|è noto che)\b",
    re.IGNORECASE,
)

# Future projections without source
_SPECULATIVE_RE = re.compile(
    r"\b(by\s+(?:20\d{2}|the\s+year\s+20\d{2})|"
    r"entro\s+(?:20\d{2}|il\s+20\d{2})|"
    r"si stima che|si prevede che|expected to|projected to)\b",
    re.IGNORECASE,
)

# Wide ranges indicating imprecision (e.g. "between 10 and 100 million")
_VAGUE_RANGE_RE = re.compile(
    r"\b(between\s+\d+\s+and\s+\d+|"
    r"\d+\s*(?:-|to|–)\s*\d+\s*(?:million|billion|milioni|miliardi)|"
    r"up to\s+\d+|più di\s+\d+|meno di\s+\d+)\b",
    re.IGNORECASE,
)

# AI-generated content without disclaimer.
#
# gap #4.16.3: this used to match the bare product names (chatgpt|claude|bard|gemini|
# copilot), so any page that merely *wrote about* AI search was flagged as undisclosed
# AI content — which is precisely this tool's own audience. Only the assistant name
# paired with an authoring verb counts as a claim of generated content; a naked mention
# does not.
_AI_GENERATED_RE = re.compile(
    r"\b(ai[- ]?generated|"
    r"generated by ai|"
    r"(?:written|generated|created|produced|authored|drafted)\s+"
    r"(?:by|with|using)\s+"
    r"(?:ai|an ai|chatgpt|claude|bard|gemini|copilot|an llm|a language model))\b",
    re.IGNORECASE,
)

# Self-citations (circular references)
_SELF_CITATION_RE = re.compile(
    r"\b(according to our (?:data|research|study)|"
    r"come riportato dal nostro (?:studio|team))\b",
    re.IGNORECASE,
)

# Missing or ambiguous units
_MISSING_UNITS_RE = re.compile(
    r"\b(\d+\.?\d*)\s*(?:times|volte)?\s*(?:faster|slower|bigger|smaller|"
    r"più (?:veloce|lento|grande|piccolo))\b",
    re.IGNORECASE,
)

# Medical claims without disclaimer
_MEDICAL_CLAIM_RE = re.compile(
    r"\b(cures?|treats?|prevents?|heals?|riduce|elimina|"
    r"guarisce|previene)\s+(?:il |la |lo )?\w+\b",
    re.IGNORECASE,
)


@dataclass
class HallucinationBaitResult:
    """Result of hallucination-bait analysis (#377)."""

    checked: bool = False
    total_baits: int = 0
    severity: str = "clean"  # clean, low, medium, high
    # Per-category baits
    unsourced_stats: int = 0
    absolute_claims: int = 0
    speculative_statements: int = 0
    vague_ranges: int = 0
    ai_generated_signals: int = 0
    self_citations: int = 0
    missing_units: int = 0
    medical_claims: int = 0
    # Samples (max 3 per category)
    unsourced_stats_samples: list[str] = field(default_factory=list)
    absolute_claims_samples: list[str] = field(default_factory=list)
    speculative_samples: list[str] = field(default_factory=list)
    vague_range_samples: list[str] = field(default_factory=list)
    ai_generated_samples: list[str] = field(default_factory=list)
    self_citation_samples: list[str] = field(default_factory=list)
    missing_units_samples: list[str] = field(default_factory=list)
    medical_claim_samples: list[str] = field(default_factory=list)
    # Detail strings
    details: list[str] = field(default_factory=list)


def _extract_text_for_analysis(soup, content: ContentResult, meta: MetaResult) -> str:
    """Extract main content text for analysis."""
    parts: list[str] = []

    if content.h1_text:
        parts.append(content.h1_text)
    if meta.title_text:
        parts.append(meta.title_text)
    if meta.description_text:
        parts.append(meta.description_text)

    if soup is not None:
        main = soup.find("main") or soup.find("article") or soup.body
        if main:
            text = main.get_text(separator=" ", strip=True)
            parts.append(text)

    return " ".join(parts)


def _find_all_with_context(pattern: re.Pattern, text: str) -> list[str]:
    """Find all matches with surrounding context (±40 chars)."""
    matches = []
    for m in pattern.finditer(text):
        start = max(0, m.start() - 40)
        end = min(len(text), m.end() + 40)
        context = text[start:end].replace("\n", " ").strip()
        matches.append(context)
    return matches


def audit_hallucination_bait(
    soup,
    raw_html: str,
    content_result: ContentResult,
    meta_result: MetaResult,
    schema_result: SchemaResult,
) -> HallucinationBaitResult:
    """Detect patterns that may cause LLM hallucinations when citing the page.

    Args:
        soup: BeautifulSoup of the page.
        raw_html: Raw HTML string.
        content_result: Computed ContentResult.
        meta_result: Computed MetaResult.
        schema_result: Computed SchemaResult.

    Returns:
        HallucinationBaitResult with detected patterns.
    """
    result = HallucinationBaitResult()
    if soup is None:
        return result

    result.checked = True
    text = _extract_text_for_analysis(soup, content_result, meta_result)

    # ── 1: Unsourced statistics ─────────────────────────────
    unsourced = _find_all_with_context(_UNSOURCED_STAT_RE, text)
    result.unsourced_stats = len(unsourced)
    result.unsourced_stats_samples = unsourced[:3]

    # ── 2: Absolute claims ──────────────────────────────────
    abs_claims = _find_all_with_context(_ABSOLUTE_CLAIM_RE, text)
    result.absolute_claims = len(abs_claims)
    result.absolute_claims_samples = abs_claims[:3]

    # ── 3: Speculative statements ─────────────────────────
    speculative = _find_all_with_context(_SPECULATIVE_RE, text)
    result.speculative_statements = len(speculative)
    result.speculative_samples = speculative[:3]

    # ── 4: Vague ranges ───────────────────────────────────
    vague = _find_all_with_context(_VAGUE_RANGE_RE, text)
    result.vague_ranges = len(vague)
    result.vague_range_samples = vague[:3]

    # ── 5: AI-generated signals ────────────────────────────
    ai_signals = _find_all_with_context(_AI_GENERATED_RE, text)
    result.ai_generated_signals = len(ai_signals)
    # Check for missing disclaimer when AI content is detected
    has_disclaimer = bool(
        re.search(
            r"\b(disclaimer|not (?:medical|legal|financial) advice|"
            r"generated by ai|ai-assisted|not a substitute)\b",
            text,
            re.IGNORECASE,
        )
    )
    result.ai_generated_signals = len(ai_signals) if not has_disclaimer else 0
    result.ai_generated_samples = ai_signals[:3] if not has_disclaimer else []

    # ── 6: Self-citations ─────────────────────────────────
    self_cite = _find_all_with_context(_SELF_CITATION_RE, text)
    result.self_citations = len(self_cite)
    result.self_citation_samples = self_cite[:3]

    # ── 7: Missing units ─────────────────────────────────
    missing = _find_all_with_context(_MISSING_UNITS_RE, text)
    result.missing_units = len(missing)
    result.missing_units_samples = missing[:3]

    # ── 8: Medical claims ─────────────────────────────────
    medical = _find_all_with_context(_MEDICAL_CLAIM_RE, text)
    result.medical_claims = len(medical)
    result.medical_claim_samples = medical[:3]

    # ── Summary ───────────────────────────────────────────
    result.total_baits = (
        result.unsourced_stats
        + result.absolute_claims
        + result.speculative_statements
        + result.vague_ranges
        + result.ai_generated_signals
        + result.self_citations
        + result.missing_units
        + result.medical_claims
    )

    # Build details messages
    if result.unsourced_stats:
        result.details.append(f"{result.unsourced_stats} unsourced statistic(s) — add citations")
    if result.absolute_claims:
        result.details.append(f"{result.absolute_claims} absolute claim(s) without evidence")
    if result.speculative_statements:
        result.details.append(f"{result.speculative_statements} speculative projection(s)")
    if result.vague_ranges:
        result.details.append(f"{result.vague_ranges} vague range(s) — use specific values")
    if result.ai_generated_signals:
        result.details.append(f"{result.ai_generated_signals} AI-generated content without disclaimer")
    if result.self_citations:
        result.details.append(f"{result.self_citations} self-citation(s) — use external sources")
    if result.missing_units:
        result.details.append(f"{result.missing_units} measurement(s) without units")
    if result.medical_claims:
        result.details.append(f"{result.medical_claims} medical claim(s) without disclaimer")

    # Severity
    if result.total_baits >= 6:
        result.severity = "high"
    elif result.total_baits >= 3:
        result.severity = "medium"
    elif result.total_baits >= 1:
        result.severity = "low"
    else:
        result.severity = "clean"

    return result
